version: '2'
services:
  insights-diginxt:
    image: insights:0.1.0
    build: .
    links:
      - redis-diginxt
    environment:
      NODE_ENV: production
      FOR: diginxt
      REDIS_HOST: redis-diginxt
    ports:
      - 8080:8080
  redis-diginxt:
    image: redis
    # ports:
    #   - 6379:6379

 

